version: '3.8'
services:
  dynamodb:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -dbPath /home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    user: root
    ports:
      - "8000:8000"
    volumes:
      - type: volume
        source: dynamodb
        target: /home/dynamodblocal/data
  minio:
    image: minio/minio
    command: server /data --address 0.0.0.0:10020 --console-address 0.0.0.0:10021
    environment:
      - MINIO_ROOT_USER=EkikaAdmin
      - MINIO_ROOT_PASSWORD=EkikaAdmin
    volumes:
      - type: volume
        source: minio
        target: /data
    ports:
      - 10020:10020
      - 10021:10021
volumes:
  dynamodb: {}
  minio: {}
